"""Generate the two single-file deliverables (internal dev tooling).

- console-standalone.html — console.html with the relative script loader replaced
  by <script> tags pinned to the immutable v1.3.1 tag on jsDelivr, each with a
  recomputed sha384 integrity attribute. One file = the whole console; the only
  network it needs is cdn.jsdelivr.net.
- docs/user-guide-standalone.html — user-guide.html with the embedded markdown's
  relative links rewritten to absolute URLs (screenshots/examples from jsDelivr,
  repo files from GitHub), so the guide renders complete when sent as one file.

test/release-check.js verifies both stay in sync with their sources and that the
pinned integrity hashes match the current dist/ and console/ bytes.

Usage: python docs/make-standalone.py
"""
import base64
import hashlib
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
TAG = "v1.3.1"
CDN = f"https://cdn.jsdelivr.net/gh/sergeiosipov/table-validation-js@{TAG}"
GH = f"https://github.com/sergeiosipov/table-validation-js/blob/{TAG}"

SCRIPTS = [
    "dist/table-validation.js",
    "console/ui.js",
    "console/store.js",
    "console/panels.js",
    "console/results.js",
    "console/app.js",
]


def sri(rel):
    digest = hashlib.sha384((ROOT / rel).read_bytes()).digest()
    return "sha384-" + base64.b64encode(digest).decode()


def build_console():
    html = (ROOT / "console.html").read_text(encoding="utf-8")
    start_marker = "    <script>\n        // engine + console scripts"
    start = html.index(start_marker)
    end = html.index("</script>", start) + len("</script>")

    tags = "\n".join(
        f'    <script src="{CDN}/{rel}"\n'
        f'            integrity="{sri(rel)}" crossorigin="anonymous"></script>'
        for rel in SCRIPTS
    )
    block = (
        "    <!-- STANDALONE BUILD: this single file is the whole deliverable. Every\n"
        "         script is pinned to the immutable v1.3.1 tag on jsDelivr with\n"
        "         subresource integrity. Generated by docs/make-standalone.py from\n"
        "         console.html; kept in sync by test/release-check.js. -->\n"
        "    <script>\n"
        "        // a single file has no sibling worker script to load — force the\n"
        "        // engines onto the main thread (the console's normal file:// behavior)\n"
        "        window.Worker = undefined;\n"
        "    </script>\n" + tags
    )
    out = html[:start] + block + html[end:]
    (ROOT / "console-standalone.html").write_text(out, encoding="utf-8", newline="\n")
    print("console-standalone.html written")


def build_guide():
    html = (ROOT / "docs" / "user-guide.html").read_text(encoding="utf-8")
    html = html.replace(
        "<!doctype html>",
        "<!doctype html>\n<!-- STANDALONE BUILD: screenshots/examples load from the immutable\n"
        "     v1.3.1 tag on jsDelivr; repo links point at GitHub. Generated by\n"
        "     docs/make-standalone.py from user-guide.html (do not edit by hand). -->",
        1,
    )
    html = html.replace("](img/", f"]({CDN}/docs/img/")
    html = html.replace("](examples/", f"]({CDN}/docs/examples/")
    html = html.replace("](make-screenshots.py)", f"]({GH}/docs/make-screenshots.py)")
    html = html.replace("](../", f"]({GH}/")
    # the <noscript> fallback link should also leave the single file
    html = html.replace('<a href="user-guide.md">', f'<a href="{GH}/docs/user-guide.md">')
    (ROOT / "docs" / "user-guide-standalone.html").write_text(html, encoding="utf-8", newline="\n")
    print("user-guide-standalone.html written")


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    build_console()
    build_guide()
